In [1]:
import numpy as np
from hmmlearn import hmm

In [2]:
# Define Model Parameters
states = ["Rainy", "Sunny"]  # Hidden states
observations = ["Walk", "Shop", "Clean"]  # Observable events

n_states = len(states)
n_observations = len(observations)

# Transition probabilities (A)
transition_probs = np.array([
    [0.7, 0.3],  # Probabilities from Rainy -> [Rainy, Sunny]
    [0.4, 0.6]   # Probabilities from Sunny -> [Rainy, Sunny]
])

# Emission probabilities (B)
emission_probs = np.array([
    [0.1, 0.4, 0.5],  # Probabilities from Rainy -> [Walk, Shop, Clean]
    [0.6, 0.3, 0.1]   # Probabilities from Sunny -> [Walk, Shop, Clean]
])

# Initial state probabilities (π)
start_probs = np.array([0.6, 0.4])  # Probabilities for starting in [Rainy, Sunny]

# Create an HMM model
model = hmm.CategoricalHMM(n_components=n_states)
model.startprob_ = start_probs
model.transmat_ = transition_probs
model.emissionprob_ = emission_probs

# Sample a sequence of observations from the model
num_samples = 10
observations_seq, hidden_states_seq = model.sample(num_samples)

print("Generated Observation Sequence (Encoded):", observations_seq.flatten())
print("Generated Hidden State Sequence:", hidden_states_seq)

# Decode the most likely hidden state sequence using Viterbi Algorithm
logprob, decoded_states = model.decode(observations_seq, algorithm="viterbi")
print("Decoded Hidden State Sequence:", decoded_states)


Generated Observation Sequence (Encoded): [2 0 2 1 2 1 2 2 1 2]
Generated Hidden State Sequence: [0 0 0 0 0 0 0 0 0 0]
Decoded Hidden State Sequence: [0 1 0 0 0 0 0 0 0 0]


In [3]:
# Define observations (encoded as numbers)
observation_dict = {"Walk": 0, "Shop": 1, "Clean": 2}
observations = np.array([
    [0, 1, 2, 0, 0, 2, 1],  # Sequence 1 (Walk, Shop, Clean, Walk, Walk, Clean, Shop)
    [2, 2, 1, 0, 1, 2, 0],  # Sequence 2 (Clean, Clean, Shop, Walk, Shop, Clean, Walk)
]) 

lengths = [len(seq) for seq in observations]  # Length of each sequence
observations = np.concatenate(observations).reshape(-1, 1)  # Flatten observations

# Create and train an HMM
model = hmm.CategoricalHMM(n_components=2, n_iter=100, random_state=42)
model.fit(observations, lengths)

# Print learned parameters
print("Learned Transition Matrix (A):\n", model.transmat_)
print("Learned Emission Matrix (B):\n", model.emissionprob_)
print("Learned Start Probabilities (π):\n", model.startprob_)

# Predict hidden states for a new observation sequence
new_observations = np.array([[0], [1], [2], [0], [1]])  # (Walk, Shop, Clean, Walk, Shop)
logprob, predicted_states = model.decode(new_observations, algorithm="viterbi")

print("\nPredicted Hidden States for New Observations:", predicted_states)

Learned Transition Matrix (A):
 [[7.52644183e-01 2.47355817e-01]
 [9.99657744e-01 3.42255731e-04]]
Learned Emission Matrix (B):
 [[2.75824506e-01 4.01348274e-01 3.22827220e-01]
 [5.58064013e-01 6.15012836e-06 4.41929837e-01]]
Learned Start Probabilities (π):
 [0.00465273 0.99534727]

Predicted Hidden States for New Observations: [1 0 0 0 0]
